INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Sam', 'sam@gmail.com', 'tweetuser1');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Tom', 'tom@gmail.com', 'tweetuser2');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Rob', 'rob@gmail.com', 'tweetuser3');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Ram', 'ram@gmail.com', 'tweetuser4');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Jon', 'jon@gmail.com', 'tweetuser5');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Tim', 'tim@gmail.com', 'tweetuser6');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Pat', 'pat@gmail.com', 'tweetuser7');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Tom', 'tom@gmail.com', 'tweetuser8');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Mel', 'mel@gmail.com', 'tweetuser9');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Abe', 'abe@gmail.com', 'tweetuser10');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Amy', 'amy@gmail.com', 'tweetuser11');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Bob', 'bob@gmail.com', 'tweetuser12');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Cam', 'cam@gmail.com', 'tweetuser13');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Jim', 'jim@gmail.com', 'tweetuser14');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Hal', 'hal@gmail.com', 'tweetuser15');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Kim', 'kim@gmail.com', 'tweetuser16');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Kit', 'kit@gmail.com', 'tweetuser17');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Ned', 'ned@gmail.com', 'tweetuser18');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Joe', 'joe@gmail.com', 'tweetuser19');
INSERT INTO TWEETUSER (user_name, user_email,user_handle) VALUES ('Pam', 'pam@gmail.com', 'tweetuser20');
COMMIT;



INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Streamlined discrete functionalities',CURRENT_TIMESTAMP,null,'pbs.org',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Re-contextualized 3rd generation projection',CURRENT_TIMESTAMP,'http://dummyimage.com/203x210.png/5fa2dd/ffffff','w3.org',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Progressive next generation data-warehouse',CURRENT_TIMESTAMP,'http://dummyimage.com/185x163.png/cc0000/ffffff','cpanel.net',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Devolved didactic extranet',CURRENT_TIMESTAMP,null,'xrea.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Distributed radical extranet',CURRENT_TIMESTAMP,'http://dummyimage.com/141x182.png/5fa2dd/ffffff','diigo.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Sharable even-keeled success',CURRENT_TIMESTAMP,'http://dummyimage.com/209x151.png/dddddd/000000','va.gov',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Fundamental web-enabled internet solution',CURRENT_TIMESTAMP,null,'xrea.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Visionary 6th generation superstructure',CURRENT_TIMESTAMP,'http://dummyimage.com/132x146.png/cc0000/ffffff','angelfire.com',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Streamlined impactful archive',CURRENT_TIMESTAMP,'http://dummyimage.com/143x117.png/ff4444/ffffff','edublogs.org',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Customer-focused content-based model',CURRENT_TIMESTAMP,'http://dummyimage.com/192x150.png/ff4444/ffffff','merriam-webster.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Secured composite capacity',CURRENT_TIMESTAMP,'http://dummyimage.com/166x238.png/dddddd/000000','drupal.org',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Focused analyzing knowledge user',CURRENT_TIMESTAMP,null,'ebay.com',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Advanced multi-state strategy',CURRENT_TIMESTAMP,'http://dummyimage.com/171x207.png/5fa2dd/ffffff','gizmodo.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Networked coherent infrastructure',CURRENT_TIMESTAMP,'http://dummyimage.com/135x187.png/cc0000/ffffff','taobao.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Implemented disintermediate attitude',CURRENT_TIMESTAMP,null,'ucoz.com',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Versatile human-resource encoding',CURRENT_TIMESTAMP,null,'statcounter.com',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Enhanced background algorithm',CURRENT_TIMESTAMP,null,'spiegel.de',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Object-based explicit local area network',CURRENT_TIMESTAMP,'http://dummyimage.com/243x102.png/dddddd/000000','yahoo.co.jp',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Fully-configurable real-time algorithm',CURRENT_TIMESTAMP,null,'dell.com',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Integrated user-facing budgetary management',CURRENT_TIMESTAMP,'http://dummyimage.com/109x237.png/dddddd/000000','live.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Public-key leading edge contingency',CURRENT_TIMESTAMP,null,'free.fr',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Centralized bi-directional service-desk',CURRENT_TIMESTAMP,'http://dummyimage.com/224x222.png/ff4444/ffffff','dmoz.org',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Face to face holistic interface',CURRENT_TIMESTAMP,'http://dummyimage.com/142x164.png/ff4444/ffffff','wired.com',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Visionary grid-enabled groupware',CURRENT_TIMESTAMP,'http://dummyimage.com/210x248.png/dddddd/000000','eepurl.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Progressive object-oriented function',CURRENT_TIMESTAMP,null,'cbc.ca',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Optimized coherent local area network',CURRENT_TIMESTAMP,'http://dummyimage.com/205x133.png/cc0000/ffffff','wisc.edu',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Mandatory 4th generation portal',CURRENT_TIMESTAMP,'http://dummyimage.com/191x194.png/5fa2dd/ffffff','berkeley.edu',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Extended fault-tolerant leverage',CURRENT_TIMESTAMP,null,'google.co.jp',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Enterprise-wide grid-enabled capacity',CURRENT_TIMESTAMP,'http://dummyimage.com/105x247.png/ff4444/ffffff','unc.edu',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Automated motivating support',CURRENT_TIMESTAMP,null,'pcworld.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Reverse-engineered real-time toolset',CURRENT_TIMESTAMP,'http://dummyimage.com/153x191.png/cc0000/ffffff','sciencedirect.com',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Implemented foreground hub',CURRENT_TIMESTAMP,'http://dummyimage.com/195x149.png/cc0000/ffffff','hao123.com',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Cross-platform cohesive emulation',CURRENT_TIMESTAMP,'http://dummyimage.com/108x158.png/ff4444/ffffff','ox.ac.uk',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Persevering encompassing encoding',CURRENT_TIMESTAMP,'http://dummyimage.com/107x184.png/dddddd/000000','friendfeed.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-channelled 24/7 website',CURRENT_TIMESTAMP,null,'fda.gov',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Horizontal solution-oriented database',CURRENT_TIMESTAMP,'http://dummyimage.com/232x202.png/cc0000/ffffff','networkadvertising.org',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Exclusive next generation conglomeration',CURRENT_TIMESTAMP,'http://dummyimage.com/233x183.png/dddddd/000000','bravesites.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Pre-emptive impactful matrices',CURRENT_TIMESTAMP,null,'bing.com',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Robust dynamic secured line',CURRENT_TIMESTAMP,'http://dummyimage.com/182x174.png/ff4444/ffffff','uol.com.br',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Vision-oriented real-time encoding',CURRENT_TIMESTAMP,'http://dummyimage.com/227x236.png/ff4444/ffffff','scribd.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Expanded composite complexity',CURRENT_TIMESTAMP,'http://dummyimage.com/207x134.png/5fa2dd/ffffff','earthlink.net',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Digitized radical product',CURRENT_TIMESTAMP,null,'google.co.jp',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Front-line mobile matrix',CURRENT_TIMESTAMP,'http://dummyimage.com/174x237.png/5fa2dd/ffffff','nbcnews.com',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Reverse-engineered client-server internet solution',CURRENT_TIMESTAMP,null,'stumbleupon.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Digitized responsive flexibility',CURRENT_TIMESTAMP,'http://dummyimage.com/231x227.png/dddddd/000000','house.gov',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Visionary maximized project',CURRENT_TIMESTAMP,'http://dummyimage.com/153x167.png/5fa2dd/ffffff','washingtonpost.com',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Synchronised multimedia architecture',CURRENT_TIMESTAMP,null,'yale.edu',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Intuitive interactive hub',CURRENT_TIMESTAMP,null,'dagondesign.com',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Re-contextualized foreground knowledge base',CURRENT_TIMESTAMP,'http://dummyimage.com/121x197.png/cc0000/ffffff','xinhuanet.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Reduced fault-tolerant capacity',CURRENT_TIMESTAMP,'http://dummyimage.com/130x130.png/ff4444/ffffff','msn.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Configurable disintermediate focus group',CURRENT_TIMESTAMP,'http://dummyimage.com/139x101.png/cc0000/ffffff','histats.com',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Public-key encompassing focus group',CURRENT_TIMESTAMP,null,'wikipedia.org',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Profit-focused 5th generation focus group',CURRENT_TIMESTAMP,'http://dummyimage.com/236x131.png/ff4444/ffffff','chicagotribune.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Polarised bandwidth-monitored knowledge base',CURRENT_TIMESTAMP,'http://dummyimage.com/240x103.png/dddddd/000000','google.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Networked empowering adapter',CURRENT_TIMESTAMP,'http://dummyimage.com/241x201.png/dddddd/000000','mac.com',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Inverse solution-oriented extranet',CURRENT_TIMESTAMP,null,'blog.com',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Programmable 6th generation secured line',CURRENT_TIMESTAMP,'http://dummyimage.com/212x166.png/dddddd/000000','ask.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Phased disintermediate methodology',CURRENT_TIMESTAMP,'http://dummyimage.com/235x126.png/ff4444/ffffff','dmoz.org',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Mandatory full-range matrices',CURRENT_TIMESTAMP,null,'clickbank.net',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Compatible next generation Graphic Interface',CURRENT_TIMESTAMP,'http://dummyimage.com/207x200.png/dddddd/000000','newyorker.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Synergized human-resource product',CURRENT_TIMESTAMP,'http://dummyimage.com/169x115.png/5fa2dd/ffffff','taobao.com',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Organized well-modulated Graphical User Interface',CURRENT_TIMESTAMP,'http://dummyimage.com/193x227.png/dddddd/000000','com.com',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Intuitive clear-thinking help-desk',CURRENT_TIMESTAMP,'http://dummyimage.com/208x227.png/ff4444/ffffff','diigo.com',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Business-focused radical algorithm',CURRENT_TIMESTAMP,null,'google.ca',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Business-focused grid-enabled website',CURRENT_TIMESTAMP,'http://dummyimage.com/190x202.png/dddddd/000000','reference.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Automated system-worthy core',CURRENT_TIMESTAMP,'http://dummyimage.com/245x150.png/ff4444/ffffff','mysql.com',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Inverse intangible projection',CURRENT_TIMESTAMP,'http://dummyimage.com/210x148.png/cc0000/ffffff','google.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Organic coherent hardware',CURRENT_TIMESTAMP,null,'patch.com',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Ergonomic composite circuit',CURRENT_TIMESTAMP,'http://dummyimage.com/182x118.png/dddddd/000000','spotify.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Horizontal encompassing software',CURRENT_TIMESTAMP,'http://dummyimage.com/106x218.png/ff4444/ffffff','examiner.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Face to face client-server model',CURRENT_TIMESTAMP,'http://dummyimage.com/138x111.png/cc0000/ffffff','acquirethisname.com',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Public-key grid-enabled matrices',CURRENT_TIMESTAMP,null,'tiny.cc',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-channelled secondary circuit',CURRENT_TIMESTAMP,null,'istockphoto.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Total clear-thinking concept',CURRENT_TIMESTAMP,'http://dummyimage.com/244x199.png/cc0000/ffffff','google.co.uk',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Balanced upward-trending intranet',CURRENT_TIMESTAMP,null,'ask.com',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Implemented leading edge throughput',CURRENT_TIMESTAMP,null,'i2i.jp',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Versatile composite service-desk',CURRENT_TIMESTAMP,null,'creativecommons.org',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Diverse needs-based productivity',CURRENT_TIMESTAMP,null,'tripod.com',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Decentralized bi-directional artificial intelligence',CURRENT_TIMESTAMP,null,'washingtonpost.com',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Realigned zero defect firmware',CURRENT_TIMESTAMP,null,'microsoft.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Secured real-time utilisation',CURRENT_TIMESTAMP,'http://dummyimage.com/248x240.png/dddddd/000000','businesswire.com',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Programmable even-keeled conglomeration',CURRENT_TIMESTAMP,null,'theatlantic.com',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('User-centric content-based process improvement',CURRENT_TIMESTAMP,'http://dummyimage.com/122x189.png/5fa2dd/ffffff','cornell.edu',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Persistent logistical time-frame',CURRENT_TIMESTAMP,null,'ftc.gov',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Re-engineered systemic budgetary management',CURRENT_TIMESTAMP,null,'wiley.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Expanded directional solution',CURRENT_TIMESTAMP,null,'domainmarket.com',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Integrated modular conglomeration',CURRENT_TIMESTAMP,null,'jalbum.net',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Automated secondary model',CURRENT_TIMESTAMP,'http://dummyimage.com/172x161.png/cc0000/ffffff','redcross.org',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Inverse zero tolerance alliance',CURRENT_TIMESTAMP,null,'google.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Right-sized transitional benchmark',CURRENT_TIMESTAMP,null,'ustream.tv',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Cloned client-driven monitoring',CURRENT_TIMESTAMP,'http://dummyimage.com/197x228.png/ff4444/ffffff','aol.com',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Public-key impactful portal',CURRENT_TIMESTAMP,'http://dummyimage.com/120x232.png/cc0000/ffffff','earthlink.net',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Balanced scalable system engine',CURRENT_TIMESTAMP,null,'cargocollective.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Visionary multimedia process improvement',CURRENT_TIMESTAMP,'http://dummyimage.com/209x233.png/dddddd/000000','geocities.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Persistent demand-driven hardware',CURRENT_TIMESTAMP,null,'ibm.com',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Synergized hybrid contingency',CURRENT_TIMESTAMP,'http://dummyimage.com/230x109.png/5fa2dd/ffffff','usatoday.com',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Re-contextualized multimedia success',CURRENT_TIMESTAMP,'http://dummyimage.com/246x138.png/5fa2dd/ffffff','soup.io',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Networked 4th generation workforce',CURRENT_TIMESTAMP,'http://dummyimage.com/142x206.png/dddddd/000000','ft.com',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Mandatory maximized time-frame',CURRENT_TIMESTAMP,'http://dummyimage.com/210x227.png/ff4444/ffffff','ftc.gov',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Managed actuating concept',CURRENT_TIMESTAMP,'http://dummyimage.com/193x204.png/cc0000/ffffff','cbslocal.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Streamlined local service-desk',CURRENT_TIMESTAMP,null,'multiply.com',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Secured client-server extranet',CURRENT_TIMESTAMP,'http://dummyimage.com/202x207.png/cc0000/ffffff','elpais.com',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Ameliorated multi-state access',CURRENT_TIMESTAMP,null,'cpanel.net',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Intuitive tertiary encoding',CURRENT_TIMESTAMP,'http://dummyimage.com/229x128.png/5fa2dd/ffffff','sphinn.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Reduced eco-centric alliance',CURRENT_TIMESTAMP,null,'macromedia.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Visionary dynamic encryption',CURRENT_TIMESTAMP,'http://dummyimage.com/125x156.png/ff4444/ffffff','cam.ac.uk',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('User-friendly grid-enabled projection',CURRENT_TIMESTAMP,'http://dummyimage.com/157x238.png/dddddd/000000','facebook.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Grass-roots empowering solution',CURRENT_TIMESTAMP,'http://dummyimage.com/114x151.png/5fa2dd/ffffff','bluehost.com',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Function-based system-worthy hub',CURRENT_TIMESTAMP,'http://dummyimage.com/213x188.png/5fa2dd/ffffff','elpais.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Public-key real-time pricing structure',CURRENT_TIMESTAMP,'http://dummyimage.com/176x128.png/dddddd/000000','weibo.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Networked homogeneous array',CURRENT_TIMESTAMP,'http://dummyimage.com/195x248.png/ff4444/ffffff','ftc.gov',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Grass-roots heuristic capability',CURRENT_TIMESTAMP,'http://dummyimage.com/244x217.png/cc0000/ffffff','ucsd.edu',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Synchronised optimizing infrastructure',CURRENT_TIMESTAMP,'http://dummyimage.com/238x103.png/5fa2dd/ffffff','oakley.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Assimilated needs-based utilisation',CURRENT_TIMESTAMP,'http://dummyimage.com/111x181.png/dddddd/000000','posterous.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Reduced web-enabled architecture',CURRENT_TIMESTAMP,'http://dummyimage.com/107x243.png/cc0000/ffffff','odnoklassniki.ru',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Re-engineered responsive contingency',CURRENT_TIMESTAMP,'http://dummyimage.com/162x170.png/cc0000/ffffff','yahoo.com',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Self-enabling motivating productivity',CURRENT_TIMESTAMP,'http://dummyimage.com/105x231.png/cc0000/ffffff','msn.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Seamless user-facing array',CURRENT_TIMESTAMP,'http://dummyimage.com/102x227.png/ff4444/ffffff','wikipedia.org',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Intuitive modular knowledge user',CURRENT_TIMESTAMP,null,'technorati.com',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Sharable high-level ability',CURRENT_TIMESTAMP,'http://dummyimage.com/242x156.png/5fa2dd/ffffff','home.pl',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Reactive fresh-thinking focus group',CURRENT_TIMESTAMP,null,'yellowbook.com',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Managed real-time emulation',CURRENT_TIMESTAMP,'http://dummyimage.com/108x232.png/ff4444/ffffff','yolasite.com',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Object-based object-oriented synergy',CURRENT_TIMESTAMP,'http://dummyimage.com/126x194.png/5fa2dd/ffffff','jimdo.com',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Polarised impactful forecast',CURRENT_TIMESTAMP,'http://dummyimage.com/123x249.png/ff4444/ffffff','netvibes.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Polarised interactive website',CURRENT_TIMESTAMP,'http://dummyimage.com/231x108.png/cc0000/ffffff','apache.org',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Optional reciprocal benchmark',CURRENT_TIMESTAMP,null,'github.com',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Organized incremental Graphic Interface',CURRENT_TIMESTAMP,'http://dummyimage.com/222x228.png/cc0000/ffffff','oracle.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Realigned fresh-thinking hardware',CURRENT_TIMESTAMP,'http://dummyimage.com/203x103.png/5fa2dd/ffffff','narod.ru',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Up-sized interactive implementation',CURRENT_TIMESTAMP,'http://dummyimage.com/178x172.png/ff4444/ffffff','feedburner.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Operative high-level adapter',CURRENT_TIMESTAMP,'http://dummyimage.com/161x167.png/cc0000/ffffff','devhub.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Pre-emptive context-sensitive paradigm',CURRENT_TIMESTAMP,null,'spotify.com',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Synergistic grid-enabled matrices',CURRENT_TIMESTAMP,'http://dummyimage.com/185x246.png/cc0000/ffffff','cpanel.net',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Horizontal eco-centric array',CURRENT_TIMESTAMP,'http://dummyimage.com/233x209.png/dddddd/000000','list-manage.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-layered intermediate neural-net',CURRENT_TIMESTAMP,'http://dummyimage.com/109x134.png/5fa2dd/ffffff','hibu.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Down-sized radical matrices',CURRENT_TIMESTAMP,'http://dummyimage.com/130x180.png/ff4444/ffffff','elegantthemes.com',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Centralized coherent paradigm',CURRENT_TIMESTAMP,null,'wix.com',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Public-key discrete algorithm',CURRENT_TIMESTAMP,'http://dummyimage.com/144x148.png/dddddd/000000','163.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Intuitive cohesive encoding',CURRENT_TIMESTAMP,'http://dummyimage.com/235x166.png/5fa2dd/ffffff','over-blog.com',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Compatible explicit architecture',CURRENT_TIMESTAMP,'http://dummyimage.com/114x233.png/cc0000/ffffff','smh.com.au',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Optional non-volatile extranet',CURRENT_TIMESTAMP,'http://dummyimage.com/212x245.png/ff4444/ffffff','baidu.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Visionary grid-enabled leverage',CURRENT_TIMESTAMP,'http://dummyimage.com/182x162.png/cc0000/ffffff','china.com.cn',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Balanced bifurcated model',CURRENT_TIMESTAMP,'http://dummyimage.com/180x108.png/dddddd/000000','bravesites.com',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Managed maximized core',CURRENT_TIMESTAMP,'http://dummyimage.com/206x208.png/5fa2dd/ffffff','furl.net',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('De-engineered hybrid installation',CURRENT_TIMESTAMP,'http://dummyimage.com/161x109.png/ff4444/ffffff','behance.net',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Stand-alone local solution',CURRENT_TIMESTAMP,'http://dummyimage.com/209x188.png/dddddd/000000','disqus.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Seamless directional artificial intelligence',CURRENT_TIMESTAMP,'http://dummyimage.com/201x130.png/dddddd/000000','weebly.com',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-layered modular paradigm',CURRENT_TIMESTAMP,'http://dummyimage.com/102x164.png/cc0000/ffffff','indiatimes.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Enhanced bifurcated orchestration',CURRENT_TIMESTAMP,'http://dummyimage.com/145x213.png/dddddd/000000','craigslist.org',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Progressive object-oriented adapter',CURRENT_TIMESTAMP,'http://dummyimage.com/220x207.png/5fa2dd/ffffff','bloomberg.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Assimilated zero tolerance methodology',CURRENT_TIMESTAMP,'http://dummyimage.com/204x184.png/5fa2dd/ffffff','nsw.gov.au',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Extended cohesive utilisation',CURRENT_TIMESTAMP,'http://dummyimage.com/151x155.png/dddddd/000000','jiathis.com',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Balanced 24/7 model',CURRENT_TIMESTAMP,'http://dummyimage.com/181x165.png/cc0000/ffffff','youtu.be',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Re-engineered global methodology',CURRENT_TIMESTAMP,'http://dummyimage.com/173x116.png/cc0000/ffffff','house.gov',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Upgradable needs-based capability',CURRENT_TIMESTAMP,'http://dummyimage.com/239x141.png/cc0000/ffffff','paypal.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Adaptive incremental software',CURRENT_TIMESTAMP,null,'amazon.com',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Profound bottom-line secured line',CURRENT_TIMESTAMP,'http://dummyimage.com/237x239.png/5fa2dd/ffffff','webmd.com',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Robust empowering help-desk',CURRENT_TIMESTAMP,null,'constantcontact.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Robust asymmetric data-warehouse',CURRENT_TIMESTAMP,'http://dummyimage.com/137x173.png/dddddd/000000','google.co.jp',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Networked bifurcated concept',CURRENT_TIMESTAMP,'http://dummyimage.com/199x150.png/dddddd/000000','nature.com',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Upgradable hybrid artificial intelligence',CURRENT_TIMESTAMP,'http://dummyimage.com/167x205.png/5fa2dd/ffffff','deviantart.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Pre-emptive global matrix',CURRENT_TIMESTAMP,null,'blogspot.com',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Ameliorated system-worthy Graphical User Interface',CURRENT_TIMESTAMP,'http://dummyimage.com/211x202.png/dddddd/000000','webeden.co.uk',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Public-key 24/7 time-frame',CURRENT_TIMESTAMP,'http://dummyimage.com/176x207.png/dddddd/000000','wufoo.com',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Persevering neutral methodology',CURRENT_TIMESTAMP,null,'europa.eu',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Operative well-modulated attitude',CURRENT_TIMESTAMP,null,'cbslocal.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Face to face bottom-line alliance',CURRENT_TIMESTAMP,'http://dummyimage.com/228x247.png/ff4444/ffffff','oracle.com',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Advanced uniform encoding',CURRENT_TIMESTAMP,'http://dummyimage.com/205x102.png/cc0000/ffffff','newyorker.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Monitored system-worthy ability',CURRENT_TIMESTAMP,'http://dummyimage.com/167x209.png/cc0000/ffffff','ovh.net',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Diverse next generation access',CURRENT_TIMESTAMP,'http://dummyimage.com/184x198.png/ff4444/ffffff','4shared.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Organized tertiary hierarchy',CURRENT_TIMESTAMP,null,'a8.net',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Intuitive analyzing matrix',CURRENT_TIMESTAMP,'http://dummyimage.com/168x212.png/ff4444/ffffff','usatoday.com',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Decentralized discrete matrices',CURRENT_TIMESTAMP,null,'networksolutions.com',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('User-centric optimizing forecast',CURRENT_TIMESTAMP,null,'oakley.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Devolved high-level collaboration',CURRENT_TIMESTAMP,'http://dummyimage.com/165x246.png/ff4444/ffffff','weibo.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Decentralized foreground encoding',CURRENT_TIMESTAMP,null,'51.la',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Sharable bi-directional forecast',CURRENT_TIMESTAMP,'http://dummyimage.com/113x203.png/cc0000/ffffff','php.net',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Balanced well-modulated projection',CURRENT_TIMESTAMP,'http://dummyimage.com/233x170.png/5fa2dd/ffffff','ning.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Business-focused mobile time-frame',CURRENT_TIMESTAMP,'http://dummyimage.com/145x123.png/dddddd/000000','twitter.com',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Extended actuating firmware',CURRENT_TIMESTAMP,'http://dummyimage.com/239x143.png/cc0000/ffffff','hugedomains.com',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Managed maximized archive',CURRENT_TIMESTAMP,'http://dummyimage.com/162x119.png/ff4444/ffffff','un.org',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-channelled object-oriented challenge',CURRENT_TIMESTAMP,null,'de.vu',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Down-sized web-enabled monitoring',CURRENT_TIMESTAMP,'http://dummyimage.com/114x227.png/dddddd/000000','hubpages.com',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Horizontal bottom-line collaboration',CURRENT_TIMESTAMP,null,'sakura.ne.jp',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Programmable user-facing knowledge base',CURRENT_TIMESTAMP,'http://dummyimage.com/184x212.png/5fa2dd/ffffff','hugedomains.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Distributed user-facing frame',CURRENT_TIMESTAMP,'http://dummyimage.com/156x190.png/dddddd/000000','vinaora.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Up-sized 3rd generation toolset',CURRENT_TIMESTAMP,null,'pagesperso-orange.fr',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Mandatory national Graphic Interface',CURRENT_TIMESTAMP,'http://dummyimage.com/246x187.png/cc0000/ffffff','printfriendly.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Switchable demand-driven data-warehouse',CURRENT_TIMESTAMP,'http://dummyimage.com/205x243.png/ff4444/ffffff','bbc.co.uk',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Vision-oriented high-level policy',CURRENT_TIMESTAMP,'http://dummyimage.com/131x203.png/dddddd/000000','pagesperso-orange.fr',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Polarised executive conglomeration',CURRENT_TIMESTAMP,null,'squidoo.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Open-source tertiary paradigm',CURRENT_TIMESTAMP,'http://dummyimage.com/181x240.png/5fa2dd/ffffff','yale.edu',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Virtual responsive migration',CURRENT_TIMESTAMP,'http://dummyimage.com/164x233.png/5fa2dd/ffffff','walmart.com',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Digitized hybrid superstructure',CURRENT_TIMESTAMP,'http://dummyimage.com/237x191.png/ff4444/ffffff','nba.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Enhanced radical neural-net',CURRENT_TIMESTAMP,'http://dummyimage.com/168x132.png/dddddd/000000','mashable.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Digitized bi-directional software',CURRENT_TIMESTAMP,'http://dummyimage.com/230x143.png/dddddd/000000','zdnet.com',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Up-sized attitude-oriented parallelism',CURRENT_TIMESTAMP,'http://dummyimage.com/169x153.png/5fa2dd/ffffff','fastcompany.com',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Organized composite Graphical User Interface',CURRENT_TIMESTAMP,'http://dummyimage.com/135x129.png/cc0000/ffffff','hao123.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Streamlined intermediate initiative',CURRENT_TIMESTAMP,null,'deliciousdays.com',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Managed modular extranet',CURRENT_TIMESTAMP,'http://dummyimage.com/127x170.png/dddddd/000000','theguardian.com',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Up-sized analyzing definition',CURRENT_TIMESTAMP,'http://dummyimage.com/242x182.png/cc0000/ffffff','telegraph.co.uk',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Stand-alone human-resource encryption',CURRENT_TIMESTAMP,'http://dummyimage.com/142x246.png/dddddd/000000','wordpress.org',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Optional foreground database',CURRENT_TIMESTAMP,null,'loc.gov',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Visionary systemic access',CURRENT_TIMESTAMP,'http://dummyimage.com/116x230.png/dddddd/000000','sciencedirect.com',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Robust bi-directional hub',CURRENT_TIMESTAMP,'http://dummyimage.com/200x107.png/cc0000/ffffff','zimbio.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Up-sized stable hardware',CURRENT_TIMESTAMP,'http://dummyimage.com/154x131.png/5fa2dd/ffffff','diigo.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Managed client-driven success',CURRENT_TIMESTAMP,'http://dummyimage.com/146x109.png/ff4444/ffffff','cdc.gov',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Organized coherent matrices',CURRENT_TIMESTAMP,'http://dummyimage.com/162x183.png/5fa2dd/ffffff','yellowpages.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Profound static utilisation',CURRENT_TIMESTAMP,'http://dummyimage.com/205x184.png/dddddd/000000','mail.ru',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Object-based zero tolerance initiative',CURRENT_TIMESTAMP,null,'cafepress.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Progressive modular system engine',CURRENT_TIMESTAMP,'http://dummyimage.com/125x104.png/dddddd/000000','tumblr.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-lateral static leverage',CURRENT_TIMESTAMP,'http://dummyimage.com/150x148.png/ff4444/ffffff','mit.edu',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Seamless systemic instruction set',CURRENT_TIMESTAMP,'http://dummyimage.com/199x108.png/5fa2dd/ffffff','sbwire.com',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Team-oriented disintermediate encoding',CURRENT_TIMESTAMP,'http://dummyimage.com/209x100.png/5fa2dd/ffffff','digg.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Open-architected motivating encryption',CURRENT_TIMESTAMP,null,'seattletimes.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Right-sized modular pricing structure',CURRENT_TIMESTAMP,'http://dummyimage.com/235x126.png/ff4444/ffffff','hhs.gov',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Cross-group system-worthy capacity',CURRENT_TIMESTAMP,null,'pcworld.com',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Monitored asynchronous product',CURRENT_TIMESTAMP,'http://dummyimage.com/103x246.png/cc0000/ffffff','businessinsider.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Cross-platform incremental hub',CURRENT_TIMESTAMP,'http://dummyimage.com/106x160.png/dddddd/000000','wikipedia.org',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Customer-focused optimizing conglomeration',CURRENT_TIMESTAMP,null,'virginia.edu',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Business-focused attitude-oriented project',CURRENT_TIMESTAMP,'http://dummyimage.com/162x215.png/dddddd/000000','webmd.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-channelled coherent definition',CURRENT_TIMESTAMP,'http://dummyimage.com/216x178.png/cc0000/ffffff','mozilla.org',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Streamlined non-volatile interface',CURRENT_TIMESTAMP,'http://dummyimage.com/235x143.png/cc0000/ffffff','google.com.br',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Customer-focused transitional extranet',CURRENT_TIMESTAMP,null,'diigo.com',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Business-focused even-keeled portal',CURRENT_TIMESTAMP,'http://dummyimage.com/135x143.png/ff4444/ffffff','shutterfly.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Visionary scalable monitoring',CURRENT_TIMESTAMP,'http://dummyimage.com/211x235.png/cc0000/ffffff','sakura.ne.jp',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Progressive full-range architecture',CURRENT_TIMESTAMP,null,'so-net.ne.jp',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Enterprise-wide tertiary middleware',CURRENT_TIMESTAMP,'http://dummyimage.com/237x178.png/5fa2dd/ffffff','bloglines.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Team-oriented logistical project',CURRENT_TIMESTAMP,'http://dummyimage.com/199x174.png/5fa2dd/ffffff','nymag.com',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Grass-roots even-keeled throughput',CURRENT_TIMESTAMP,null,'godaddy.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Profound demand-driven matrices',CURRENT_TIMESTAMP,null,'purevolume.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Switchable systemic local area network',CURRENT_TIMESTAMP,'http://dummyimage.com/241x109.png/5fa2dd/ffffff','pbs.org',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Progressive systematic approach',CURRENT_TIMESTAMP,'http://dummyimage.com/244x184.png/5fa2dd/ffffff','csmonitor.com',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Optional national adapter',CURRENT_TIMESTAMP,null,'icio.us',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Visionary holistic protocol',CURRENT_TIMESTAMP,'http://dummyimage.com/188x228.png/cc0000/ffffff','hexun.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Automated fresh-thinking concept',CURRENT_TIMESTAMP,'http://dummyimage.com/157x238.png/5fa2dd/ffffff','sourceforge.net',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Enhanced client-server moderator',CURRENT_TIMESTAMP,'http://dummyimage.com/166x243.png/dddddd/000000','engadget.com',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Synchronised human-resource secured line',CURRENT_TIMESTAMP,'http://dummyimage.com/202x111.png/5fa2dd/ffffff','ibm.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Synchronised transitional artificial intelligence',CURRENT_TIMESTAMP,'http://dummyimage.com/196x188.png/dddddd/000000','oaic.gov.au',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Operative needs-based collaboration',CURRENT_TIMESTAMP,'http://dummyimage.com/159x191.png/cc0000/ffffff','hp.com',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Enterprise-wide tangible array',CURRENT_TIMESTAMP,null,'yandex.ru',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Digitized disintermediate time-frame',CURRENT_TIMESTAMP,null,'t.co',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Persevering asymmetric moratorium',CURRENT_TIMESTAMP,null,'sbwire.com',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Customer-focused 4th generation forecast',CURRENT_TIMESTAMP,null,'who.int',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Monitored hybrid pricing structure',CURRENT_TIMESTAMP,'http://dummyimage.com/141x244.png/ff4444/ffffff','deviantart.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Grass-roots encompassing benchmark',CURRENT_TIMESTAMP,null,'uol.com.br',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Diverse mission-critical toolset',CURRENT_TIMESTAMP,'http://dummyimage.com/190x109.png/5fa2dd/ffffff','omniture.com',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Automated fault-tolerant utilisation',CURRENT_TIMESTAMP,'http://dummyimage.com/244x109.png/5fa2dd/ffffff','statcounter.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Team-oriented encompassing solution',CURRENT_TIMESTAMP,'http://dummyimage.com/178x200.png/cc0000/ffffff','deviantart.com',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Switchable even-keeled architecture',CURRENT_TIMESTAMP,'http://dummyimage.com/120x245.png/dddddd/000000','nytimes.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Vision-oriented composite moratorium',CURRENT_TIMESTAMP,null,'home.pl',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Progressive disintermediate policy',CURRENT_TIMESTAMP,'http://dummyimage.com/135x241.png/dddddd/000000','omniture.com',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Versatile non-volatile array',CURRENT_TIMESTAMP,'http://dummyimage.com/205x171.png/dddddd/000000','privacy.gov.au',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Open-architected object-oriented benchmark',CURRENT_TIMESTAMP,'http://dummyimage.com/169x233.png/dddddd/000000','blogger.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Future-proofed web-enabled data-warehouse',CURRENT_TIMESTAMP,null,'omniture.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Secured intermediate support',CURRENT_TIMESTAMP,'http://dummyimage.com/143x172.png/ff4444/ffffff','i2i.jp',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Future-proofed 24/7 migration',CURRENT_TIMESTAMP,'http://dummyimage.com/100x183.png/cc0000/ffffff','smh.com.au',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Synchronised directional archive',CURRENT_TIMESTAMP,'http://dummyimage.com/102x235.png/5fa2dd/ffffff','huffingtonpost.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Horizontal multi-tasking parallelism',CURRENT_TIMESTAMP,'http://dummyimage.com/220x136.png/5fa2dd/ffffff','digg.com',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Fully-configurable disintermediate artificial intelligence',CURRENT_TIMESTAMP,'http://dummyimage.com/145x209.png/cc0000/ffffff','zdnet.com',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Streamlined dedicated budgetary management',CURRENT_TIMESTAMP,null,'independent.co.uk',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Networked impactful knowledge base',CURRENT_TIMESTAMP,null,'odnoklassniki.ru',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Digitized tangible adapter',CURRENT_TIMESTAMP,'http://dummyimage.com/191x194.png/ff4444/ffffff','i2i.jp',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Managed foreground website',CURRENT_TIMESTAMP,null,'cnn.com',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Devolved dynamic superstructure',CURRENT_TIMESTAMP,'http://dummyimage.com/187x139.png/5fa2dd/ffffff','tripod.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Re-contextualized real-time policy',CURRENT_TIMESTAMP,null,'live.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Horizontal asynchronous parallelism',CURRENT_TIMESTAMP,null,'ning.com',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Phased system-worthy hub',CURRENT_TIMESTAMP,'http://dummyimage.com/232x216.png/5fa2dd/ffffff','delicious.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Monitored 24/7 moderator',CURRENT_TIMESTAMP,'http://dummyimage.com/202x187.png/dddddd/000000','ovh.net',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Streamlined client-driven matrices',CURRENT_TIMESTAMP,'http://dummyimage.com/149x106.png/dddddd/000000','mozilla.org',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Face to face asynchronous infrastructure',CURRENT_TIMESTAMP,'http://dummyimage.com/162x222.png/5fa2dd/ffffff','webnode.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Reactive heuristic workforce',CURRENT_TIMESTAMP,'http://dummyimage.com/119x207.png/5fa2dd/ffffff','narod.ru',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Realigned context-sensitive workforce',CURRENT_TIMESTAMP,null,'jigsy.com',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('De-engineered fault-tolerant application',CURRENT_TIMESTAMP,'http://dummyimage.com/192x179.png/dddddd/000000','barnesandnoble.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Total full-range open system',CURRENT_TIMESTAMP,null,'uiuc.edu',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Virtual directional help-desk',CURRENT_TIMESTAMP,null,'about.me',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Automated intangible open system',CURRENT_TIMESTAMP,'http://dummyimage.com/244x243.png/5fa2dd/ffffff','cpanel.net',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Organic even-keeled middleware',CURRENT_TIMESTAMP,'http://dummyimage.com/100x128.png/dddddd/000000','cbslocal.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Extended neutral service-desk',CURRENT_TIMESTAMP,'http://dummyimage.com/209x152.png/cc0000/ffffff','github.com',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('User-centric maximized application',CURRENT_TIMESTAMP,'http://dummyimage.com/221x180.png/5fa2dd/ffffff','sohu.com',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Synergistic real-time leverage',CURRENT_TIMESTAMP,'http://dummyimage.com/147x174.png/cc0000/ffffff','ted.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Managed motivating strategy',CURRENT_TIMESTAMP,null,'wikispaces.com',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Managed 24/7 strategy',CURRENT_TIMESTAMP,'http://dummyimage.com/165x107.png/5fa2dd/ffffff','disqus.com',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Digitized high-level internet solution',CURRENT_TIMESTAMP,null,'flickr.com',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Future-proofed regional conglomeration',CURRENT_TIMESTAMP,'http://dummyimage.com/130x205.png/dddddd/000000','baidu.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Pre-emptive mission-critical paradigm',CURRENT_TIMESTAMP,null,'blogspot.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-layered hybrid benchmark',CURRENT_TIMESTAMP,null,'google.com.br',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Exclusive regional encryption',CURRENT_TIMESTAMP,null,'booking.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Devolved contextually-based support',CURRENT_TIMESTAMP,'http://dummyimage.com/177x198.png/5fa2dd/ffffff','123-reg.co.uk',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Robust optimizing intranet',CURRENT_TIMESTAMP,'http://dummyimage.com/222x243.png/5fa2dd/ffffff','tripadvisor.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Optimized client-driven pricing structure',CURRENT_TIMESTAMP,'http://dummyimage.com/246x215.png/5fa2dd/ffffff','independent.co.uk',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Assimilated radical database',CURRENT_TIMESTAMP,'http://dummyimage.com/114x187.png/ff4444/ffffff','nih.gov',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Cloned human-resource middleware',CURRENT_TIMESTAMP,null,'thetimes.co.uk',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Streamlined full-range functionalities',CURRENT_TIMESTAMP,'http://dummyimage.com/236x214.png/5fa2dd/ffffff','narod.ru',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Integrated cohesive conglomeration',CURRENT_TIMESTAMP,'http://dummyimage.com/206x111.png/cc0000/ffffff','reference.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Exclusive modular intranet',CURRENT_TIMESTAMP,null,'prweb.com',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Future-proofed scalable complexity',CURRENT_TIMESTAMP,'http://dummyimage.com/132x154.png/5fa2dd/ffffff','skype.com',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Persistent transitional hierarchy',CURRENT_TIMESTAMP,'http://dummyimage.com/187x176.png/5fa2dd/ffffff','hp.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Implemented zero administration matrices',CURRENT_TIMESTAMP,'http://dummyimage.com/183x156.png/5fa2dd/ffffff','google.co.uk',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Focused clear-thinking matrix',CURRENT_TIMESTAMP,'http://dummyimage.com/239x160.png/cc0000/ffffff','deliciousdays.com',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Assimilated client-server moratorium',CURRENT_TIMESTAMP,'http://dummyimage.com/128x230.png/5fa2dd/ffffff','moonfruit.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Organized coherent data-warehouse',CURRENT_TIMESTAMP,null,'sitemeter.com',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Persevering neutral implementation',CURRENT_TIMESTAMP,'http://dummyimage.com/125x157.png/ff4444/ffffff','cmu.edu',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Adaptive modular throughput',CURRENT_TIMESTAMP,null,'indiegogo.com',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Re-engineered static forecast',CURRENT_TIMESTAMP,'http://dummyimage.com/190x178.png/5fa2dd/ffffff','home.pl',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Profound local contingency',CURRENT_TIMESTAMP,'http://dummyimage.com/223x151.png/cc0000/ffffff','smh.com.au',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Visionary radical capacity',CURRENT_TIMESTAMP,'http://dummyimage.com/122x208.png/ff4444/ffffff','cyberchimps.com',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Self-enabling systematic adapter',CURRENT_TIMESTAMP,null,'de.vu',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Re-contextualized client-server success',CURRENT_TIMESTAMP,'http://dummyimage.com/160x169.png/5fa2dd/ffffff','flavors.me',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Stand-alone systematic orchestration',CURRENT_TIMESTAMP,'http://dummyimage.com/204x191.png/dddddd/000000','ted.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Focused coherent conglomeration',CURRENT_TIMESTAMP,'http://dummyimage.com/157x130.png/dddddd/000000','tamu.edu',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Synergistic incremental strategy',CURRENT_TIMESTAMP,null,'feedburner.com',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Object-based non-volatile encryption',CURRENT_TIMESTAMP,null,'is.gd',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Advanced optimal paradigm',CURRENT_TIMESTAMP,'http://dummyimage.com/235x171.png/ff4444/ffffff','vistaprint.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Object-based optimal capability',CURRENT_TIMESTAMP,null,'naver.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Synergized static knowledge base',CURRENT_TIMESTAMP,'http://dummyimage.com/153x117.png/ff4444/ffffff','msu.edu',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Optional zero administration secured line',CURRENT_TIMESTAMP,'http://dummyimage.com/184x159.png/dddddd/000000','archive.org',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-channelled asymmetric local area network',CURRENT_TIMESTAMP,'http://dummyimage.com/200x227.png/dddddd/000000','flavors.me',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Intuitive 3rd generation model',CURRENT_TIMESTAMP,'http://dummyimage.com/196x223.png/5fa2dd/ffffff','latimes.com',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Advanced didactic policy',CURRENT_TIMESTAMP,'http://dummyimage.com/195x101.png/ff4444/ffffff','jimdo.com',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Monitored intermediate service-desk',CURRENT_TIMESTAMP,null,'blinklist.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Universal bifurcated intranet',CURRENT_TIMESTAMP,'http://dummyimage.com/196x156.png/cc0000/ffffff','lulu.com',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Function-based mission-critical website',CURRENT_TIMESTAMP,null,'dailymotion.com',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Persistent even-keeled neural-net',CURRENT_TIMESTAMP,null,'webeden.co.uk',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Intuitive static parallelism',CURRENT_TIMESTAMP,null,'fda.gov',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Persistent human-resource access',CURRENT_TIMESTAMP,'http://dummyimage.com/249x247.png/cc0000/ffffff','apple.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Programmable 4th generation data-warehouse',CURRENT_TIMESTAMP,'http://dummyimage.com/229x182.png/cc0000/ffffff','posterous.com',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Optimized multimedia interface',CURRENT_TIMESTAMP,'http://dummyimage.com/156x138.png/cc0000/ffffff','about.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Optional well-modulated access',CURRENT_TIMESTAMP,null,'jimdo.com',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Universal 24/7 architecture',CURRENT_TIMESTAMP,'http://dummyimage.com/230x118.png/ff4444/ffffff','newsvine.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Devolved radical focus group',CURRENT_TIMESTAMP,'http://dummyimage.com/236x128.png/ff4444/ffffff','sitemeter.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Stand-alone systematic protocol',CURRENT_TIMESTAMP,'http://dummyimage.com/133x111.png/dddddd/000000','gravatar.com',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Sharable zero administration secured line',CURRENT_TIMESTAMP,'http://dummyimage.com/202x157.png/ff4444/ffffff','jigsy.com',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Enhanced national instruction set',CURRENT_TIMESTAMP,'http://dummyimage.com/178x234.png/cc0000/ffffff','cpanel.net',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Optional systematic software',CURRENT_TIMESTAMP,'http://dummyimage.com/163x178.png/ff4444/ffffff','mail.ru',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Configurable composite attitude',CURRENT_TIMESTAMP,'http://dummyimage.com/223x183.png/cc0000/ffffff','discuz.net',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Configurable contextually-based encryption',CURRENT_TIMESTAMP,'http://dummyimage.com/232x145.png/dddddd/000000','lycos.com',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Right-sized interactive firmware',CURRENT_TIMESTAMP,null,'google.it',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Vision-oriented maximized emulation',CURRENT_TIMESTAMP,'http://dummyimage.com/239x249.png/dddddd/000000','who.int',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Diverse value-added flexibility',CURRENT_TIMESTAMP,'http://dummyimage.com/114x139.png/5fa2dd/ffffff','mapy.cz',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Self-enabling uniform emulation',CURRENT_TIMESTAMP,null,'apache.org',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Versatile uniform focus group',CURRENT_TIMESTAMP,null,'aboutads.info',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Innovative dedicated flexibility',CURRENT_TIMESTAMP,'http://dummyimage.com/151x211.png/5fa2dd/ffffff','usatoday.com',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Cross-group fresh-thinking policy',CURRENT_TIMESTAMP,'http://dummyimage.com/223x138.png/dddddd/000000','businessweek.com',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Inverse homogeneous standardization',CURRENT_TIMESTAMP,'http://dummyimage.com/212x134.png/dddddd/000000','mail.ru',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Future-proofed systematic task-force',CURRENT_TIMESTAMP,'http://dummyimage.com/187x137.png/ff4444/ffffff','issuu.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Ergonomic local superstructure',CURRENT_TIMESTAMP,'http://dummyimage.com/143x121.png/ff4444/ffffff','paypal.com',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Automated real-time function',CURRENT_TIMESTAMP,'http://dummyimage.com/243x175.png/dddddd/000000','phpbb.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Ameliorated explicit emulation',CURRENT_TIMESTAMP,null,'uiuc.edu',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-tiered holistic circuit',CURRENT_TIMESTAMP,'http://dummyimage.com/162x131.png/dddddd/000000','pinterest.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Managed hybrid local area network',CURRENT_TIMESTAMP,'http://dummyimage.com/179x192.png/dddddd/000000','tinyurl.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Quality-focused intangible internet solution',CURRENT_TIMESTAMP,null,'vimeo.com',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Decentralized national portal',CURRENT_TIMESTAMP,null,'google.nl',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Assimilated web-enabled adapter',CURRENT_TIMESTAMP,null,'mit.edu',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('User-centric context-sensitive open system',CURRENT_TIMESTAMP,'http://dummyimage.com/190x136.png/ff4444/ffffff','is.gd',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Universal holistic info-mediaries',CURRENT_TIMESTAMP,null,'sitemeter.com',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-channelled client-server local area network',CURRENT_TIMESTAMP,'http://dummyimage.com/184x234.png/5fa2dd/ffffff','amazon.co.jp',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Re-engineered bottom-line conglomeration',CURRENT_TIMESTAMP,'http://dummyimage.com/131x106.png/cc0000/ffffff','w3.org',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Diverse human-resource concept',CURRENT_TIMESTAMP,'http://dummyimage.com/116x201.png/cc0000/ffffff','imageshack.us',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Inverse 4th generation data-warehouse',CURRENT_TIMESTAMP,null,'infoseek.co.jp',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Re-contextualized reciprocal structure',CURRENT_TIMESTAMP,'http://dummyimage.com/209x150.png/ff4444/ffffff','cnn.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Triple-buffered leading edge firmware',CURRENT_TIMESTAMP,'http://dummyimage.com/122x158.png/dddddd/000000','soup.io',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Profit-focused even-keeled success',CURRENT_TIMESTAMP,'http://dummyimage.com/116x142.png/dddddd/000000','yale.edu',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Integrated encompassing conglomeration',CURRENT_TIMESTAMP,'http://dummyimage.com/236x169.png/ff4444/ffffff','php.net',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Organic client-driven benchmark',CURRENT_TIMESTAMP,null,'acquirethisname.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-tiered homogeneous frame',CURRENT_TIMESTAMP,'http://dummyimage.com/165x246.png/dddddd/000000','un.org',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Ergonomic transitional process improvement',CURRENT_TIMESTAMP,null,'sakura.ne.jp',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Innovative demand-driven benchmark',CURRENT_TIMESTAMP,'http://dummyimage.com/225x183.png/dddddd/000000','wordpress.org',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Sharable attitude-oriented knowledge base',CURRENT_TIMESTAMP,'http://dummyimage.com/109x230.png/5fa2dd/ffffff','nsw.gov.au',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Reduced cohesive portal',CURRENT_TIMESTAMP,'http://dummyimage.com/118x164.png/dddddd/000000','oracle.com',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Upgradable interactive definition',CURRENT_TIMESTAMP,'http://dummyimage.com/224x174.png/cc0000/ffffff','xrea.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-tiered analyzing frame',CURRENT_TIMESTAMP,'http://dummyimage.com/211x166.png/5fa2dd/ffffff','webeden.co.uk',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Devolved foreground emulation',CURRENT_TIMESTAMP,'http://dummyimage.com/107x208.png/5fa2dd/ffffff','hostgator.com',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Switchable 6th generation standardization',CURRENT_TIMESTAMP,null,'newyorker.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Proactive bottom-line toolset',CURRENT_TIMESTAMP,null,'themeforest.net',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Open-source mission-critical database',CURRENT_TIMESTAMP,'http://dummyimage.com/160x155.png/5fa2dd/ffffff','1688.com',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Business-focused responsive hierarchy',CURRENT_TIMESTAMP,null,'google.com.br',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Inverse directional matrix',CURRENT_TIMESTAMP,null,'icq.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Visionary human-resource success',CURRENT_TIMESTAMP,'http://dummyimage.com/102x171.png/ff4444/ffffff','stumbleupon.com',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Total neutral Graphic Interface',CURRENT_TIMESTAMP,null,'zimbio.com',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Organized responsive open system',CURRENT_TIMESTAMP,null,'wikimedia.org',20);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-tiered methodical open system',CURRENT_TIMESTAMP,'http://dummyimage.com/189x221.png/cc0000/ffffff','microsoft.com',1);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Customizable zero tolerance software',CURRENT_TIMESTAMP,null,'indiatimes.com',2);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Profit-focused fresh-thinking data-warehouse',CURRENT_TIMESTAMP,'http://dummyimage.com/223x138.png/dddddd/000000','opera.com',3);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('User-centric real-time matrix',CURRENT_TIMESTAMP,null,'istockphoto.com',4);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Object-based optimizing core',CURRENT_TIMESTAMP,'http://dummyimage.com/179x123.png/5fa2dd/ffffff','microsoft.com',5);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Synergized local complexity',CURRENT_TIMESTAMP,'http://dummyimage.com/235x241.png/5fa2dd/ffffff','marketwatch.com',6);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Reverse-engineered even-keeled protocol',CURRENT_TIMESTAMP,'http://dummyimage.com/162x138.png/dddddd/000000','skyrock.com',7);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Multi-layered 6th generation installation',CURRENT_TIMESTAMP,null,'smugmug.com',8);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Streamlined object-oriented firmware',CURRENT_TIMESTAMP,'http://dummyimage.com/111x151.png/ff4444/ffffff','ezinearticles.com',9);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Optional motivating core',CURRENT_TIMESTAMP,'http://dummyimage.com/161x194.png/dddddd/000000','nsw.gov.au',10);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Universal 24 hour analyzer',CURRENT_TIMESTAMP,'http://dummyimage.com/152x169.png/cc0000/ffffff','sbwire.com',11);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Customer-focused even-keeled forecast',CURRENT_TIMESTAMP,'http://dummyimage.com/110x118.png/5fa2dd/ffffff','engadget.com',12);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Automated 4th generation knowledge base',CURRENT_TIMESTAMP,'http://dummyimage.com/103x133.png/5fa2dd/ffffff','i2i.jp',13);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Switchable optimal flexibility',CURRENT_TIMESTAMP,'http://dummyimage.com/216x249.png/ff4444/ffffff','bing.com',14);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Devolved maximized help-desk',CURRENT_TIMESTAMP,null,'tripod.com',15);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Grass-roots web-enabled complexity',CURRENT_TIMESTAMP,'http://dummyimage.com/217x144.png/cc0000/ffffff','sciencedaily.com',16);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Ergonomic dynamic attitude',CURRENT_TIMESTAMP,'http://dummyimage.com/176x178.png/ff4444/ffffff','home.pl',17);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Virtual discrete synergy',CURRENT_TIMESTAMP,'http://dummyimage.com/170x213.png/dddddd/000000','live.com',18);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Polarised grid-enabled matrix',CURRENT_TIMESTAMP,null,'hatena.ne.jp',19);
INSERT INTO TWEET (CONTENT, CREATED_DATE, IMAGE_URL, METADATA, USER_ID) VALUES ('Phased real-time analyzer',CURRENT_TIMESTAMP,'http://dummyimage.com/242x195.png/cc0000/ffffff','vk.com',20);
COMMIT;


INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (1,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (1,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (1,4);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (1,5);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (1,6);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (1,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (1,8);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (1,9);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (1,10);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (2,4);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (2,6);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (2,8);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (2,4);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (2,10);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (2,12);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (3,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (3,9);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (3,11);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (3,13);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (3,15);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (3,18);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (3,20);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (3,5);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (4,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (4,1);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (4,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (4,6);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (4,16);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (4,14);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (4,12);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (4,9);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (5,6);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (5,8);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (5,12);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (5,11);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (5,20);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (5,19);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (5,18);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (5,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (6,1);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (6,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (6,4);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (6,15);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (6,13);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (6,11);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (6,19);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (7,8);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (7,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (7,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (7,17);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (7,18);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (7,16);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (7,15);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (7,12);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (8,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (8,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (8,13);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (8,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (8,14);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (8,5);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (8,16);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (9,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (9,1);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (9,11);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (9,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (9,12);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (9,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (9,13);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (9,4);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (10,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (10,1);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (10,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (10,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (10,4);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (10,11);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (10,12);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (10,13);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (10,14);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (10,15);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (11,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (11,8);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (11,9);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (11,10);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (11,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (11,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (11,4);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (11,5);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (12,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (12,1);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (12,8);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (12,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (12,10);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (13,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (13,1);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (13,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (13,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (13,15);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (13,16);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (13,17);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (13,18);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (13,19);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (14,19);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (14,18);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (14,11);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (14,12);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (14,16);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (14,10);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (14,1);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (15,19);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (15,11);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (15,9);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (15,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (15,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (15,1);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (15,6);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (15,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (16,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (16,8);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (16,9);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (16,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (16,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (16,4);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (16,5);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (17,1);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (17,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (17,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (17,4);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (17,5);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (17,6);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (17,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (17,8);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (17,9);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (17,10);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (17,11);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (17,12);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (18,10);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (18,19);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (18,11);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (18,1);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (18,12);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (18,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (18,14);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (18,17);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (19,7);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (19,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (19,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (19,4);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (19,5);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (19,6);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (20,1);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (20,2);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (20,3);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (20,12);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (20,6);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (20,15);
INSERT INTO USERFOLLOWER (USER_ID, FOLLOWER_ID) VALUES (20,8);

COMMIT;