DROP TABLE IF EXISTS TWEET;
DROP TABLE IF EXISTS TWEETUSER;
DROP TABLE IF EXISTS USERFOLLOWER;


CREATE TABLE TWEETUSER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(100) NOT NULL,
  user_email VARCHAR(100) NOT NULL,
  user_handle VARCHAR(100) NOT NULL
);

CREATE TABLE TWEET (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content VARCHAR(280) NOT NULL,
  created_date DATE NOT NULL,
  image_url VARCHAR(400),
  metadata VARCHAR(400),
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES TWEETUSER(id)
);

CREATE TABLE USERFOLLOWER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  follower_id INT
);